import {test,expect} from '@playwright/test';
import fs from 'node:fs';
import path from 'node:path';
const env=Object.fromEntries(fs.readFileSync('.env','utf8').split('\n').map(line=>{const i=line.indexOf('=');return [line.slice(0,i),line.slice(i+1).replace(/^['"]|['"]$/g,'')]}));
const email=process.env.PBI_E2E_EMAIL??'admin@example.test';
const password=process.env.PBI_E2E_PASSWORD??env.PBI_E2E_PASSWORD;

test('real frontend: login, restore, import, ingest, inference, history, admin, logout',async({page})=>{
  const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
  await page.goto('/');
  await page.getByLabel('Email address').fill(email);
  await page.getByLabel('Password',{exact:true}).fill(password);
  await page.getByRole('button',{name:'Sign in'}).click();
  await expect(page.getByRole('heading',{name:'Good morning'})).toBeVisible();
  await page.reload();
  await expect(page.getByRole('heading',{name:'Good morning'})).toBeVisible();
  await page.getByRole('link',{name:'Analytics',exact:true}).click();
  await page.getByLabel('Business CSV').setInputFiles(path.resolve('data/sample/sales-import.csv'));
  await page.getByRole('button',{name:'Import CSV',exact:true}).click();
  await expect(page.getByText('3 records already imported.')).toBeVisible();
  await page.getByLabel('Import type').selectOption('expenses');
  await page.getByLabel('Business CSV').setInputFiles({name:'synthetic-browser-expenses.csv',mimeType:'text/csv',buffer:Buffer.from('category,date,amount,description\nSynthetic browser audit,2028-01-01,12.50,Labelled synthetic test expense\n')});
  await page.getByRole('button',{name:'Import CSV',exact:true}).click();
  await expect(page.getByText(/1 records (already imported|imported)\./)).toBeVisible();
  await page.getByRole('link',{name:'Documents',exact:true}).click();
  await page.locator('input[name="file"]').setInputFiles({name:'synthetic-browser-policy.txt',mimeType:'text/plain',buffer:Buffer.from('SYNTHETIC AUDIT: Internal expense policy requires receipts for all reimbursement requests. Travel above ZAR 500 requires manager approval.')});
  await page.getByRole('button',{name:'Upload & index'}).click();
  await expect(page.getByText('synthetic-browser-policy.txt was indexed successfully.')).toBeVisible({timeout:180000});
  await page.getByLabel('Search documents').fill('expense policy receipts');
  const searchResponse=page.waitForResponse(r=>r.url().endsWith('/api/search'));
  await page.getByRole('button',{name:'Search evidence'}).click();
  expect((await (await searchResponse).json()).data.results.some((s:any)=>s.filename==='synthetic-browser-policy.txt')).toBe(true);
  await page.locator('tr').filter({hasText:'synthetic-browser-policy.txt'}).getByRole('button',{name:'Manage access'}).click();
  await page.getByLabel('Document visibility').selectOption('restricted');
  const visibilityResponse=page.waitForResponse(r=>r.request().method()==='PATCH'&&r.url().includes('/api/documents/'));
  await page.getByRole('button',{name:'Save visibility'}).click();
  expect((await visibilityResponse).status()).toBe(200);
  await page.getByRole('link',{name:'AI Analyst',exact:false}).first().click();
  await page.locator('textarea').fill('What does our internal expense policy say?');
  const resultPromise=page.waitForResponse(r=>r.url().endsWith('/api/analysis')&&r.request().method()==='POST',{timeout:240000});
  await page.getByRole('button',{name:'Analyse question'}).click();
  const response=await resultPromise;expect(response.status()).toBe(200);
  const payload=await response.json();expect(payload.data.inferenceUsed).toBe(true);
  expect(payload.data.analysisType).toBe('knowledge');
  expect(payload.data.sources.some((s:any)=>s.name==='synthetic-browser-policy.txt')).toBe(true);
  await expect(page.getByRole('heading',{name:'Answer',exact:true})).toBeVisible();
  expect(payload.data.sources.some((s:any)=>s.excerpt?.includes('requires receipts'))).toBe(true);
  await page.getByRole('button',{name:/knowledge ·/}).first().click();
  await expect(page.getByRole('heading',{name:'Answer',exact:true})).toBeVisible();
  await page.getByRole('link',{name:'Administration',exact:true}).click();
  await expect(page.getByRole('heading',{name:'Workspace profile'})).toBeVisible();
  await page.getByRole('button',{name:'Audit activity'}).click();
  await expect(page.getByRole('heading',{name:'Recent activity'})).toBeVisible();
  await page.getByRole('button',{name:'Sign out'}).click();
  await expect(page.getByRole('heading',{name:'Sign in to your workspace'})).toBeVisible();
  await page.reload();
  await expect(page.getByRole('heading',{name:'Sign in to your workspace'})).toBeVisible();
  expect(errors).toEqual([]);
});

test('real frontend: create viewer, enforce navigation restrictions, disable active session',async({page,browser})=>{
  const viewerEmail=`synthetic-browser-${Date.now()}@example.test`;
  await page.goto('/');await page.getByLabel('Email address').fill(email);await page.getByLabel('Password',{exact:true}).fill(password);await page.getByRole('button',{name:'Sign in'}).click();
  await page.getByRole('link',{name:'Administration',exact:true}).click();
  await page.getByLabel('Email address').fill(viewerEmail);await page.getByLabel('Temporary password').fill(password);await page.getByLabel('Access role').selectOption('viewer');await page.getByRole('button',{name:'Create account'}).click();
  await expect(page.getByText('The account was created.',{exact:false})).toBeVisible();
  const viewerContext=await browser.newContext();const viewerPage=await viewerContext.newPage();
  await viewerPage.goto('http://localhost:5173');await viewerPage.getByLabel('Email address').fill(viewerEmail);await viewerPage.getByLabel('Password',{exact:true}).fill(password);await viewerPage.getByRole('button',{name:'Sign in'}).click();
  await expect(viewerPage.getByRole('heading',{name:'Good morning'})).toBeVisible();
  await expect(viewerPage.getByRole('link',{name:'Documents',exact:true})).toHaveCount(0);
  await expect(viewerPage.getByRole('link',{name:'Administration',exact:true})).toHaveCount(0);
  await viewerPage.goto('http://localhost:5173/admin');await expect(viewerPage.getByRole('heading',{name:'Good morning'})).toBeVisible();
  page.once('dialog',dialog=>dialog.accept());
  await page.locator('.team-row').filter({hasText:viewerEmail}).getByRole('button',{name:'Disable',exact:true}).click();
  await expect(page.locator('.team-row').filter({hasText:viewerEmail}).getByText('Disabled',{exact:true})).toBeVisible();
  await viewerPage.reload();await expect(viewerPage.getByRole('heading',{name:'Sign in to your workspace'})).toBeVisible();
  await viewerContext.close();
});
