CREATE EXTENSION IF NOT EXISTS vector;
CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE TABLE organisations(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),name text NOT NULL,created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE permissions(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),permission_key text NOT NULL UNIQUE,description text NOT NULL);
CREATE TABLE roles(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),role_key text NOT NULL UNIQUE CHECK(role_key IN ('admin','analyst','viewer')),description text NOT NULL);
CREATE TABLE role_permissions(role_id uuid NOT NULL REFERENCES roles(id) ON DELETE CASCADE,permission_id uuid NOT NULL REFERENCES permissions(id) ON DELETE CASCADE,PRIMARY KEY(role_id,permission_id));
INSERT INTO roles(role_key,description) VALUES ('admin','Organisation administrator'),('analyst','Business analysis and document upload'),('viewer','Read and ask permitted questions');
INSERT INTO permissions(permission_key,description) VALUES ('organisation.manage','Manage organisation and users'),('documents.upload','Upload and process documents'),('analysis.run','Run business analysis'),('audit.read','View security and analysis audit events');
INSERT INTO role_permissions(role_id,permission_id) SELECT r.id,p.id FROM roles r CROSS JOIN permissions p WHERE r.role_key='admin';
INSERT INTO role_permissions(role_id,permission_id) SELECT r.id,p.id FROM roles r JOIN permissions p ON p.permission_key IN ('documents.upload','analysis.run') WHERE r.role_key='analyst';
INSERT INTO role_permissions(role_id,permission_id) SELECT r.id,p.id FROM roles r JOIN permissions p ON p.permission_key='analysis.run' WHERE r.role_key='viewer';
CREATE TABLE users(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),org_id uuid NOT NULL REFERENCES organisations(id),email text NOT NULL,password_hash text NOT NULL,role text NOT NULL CHECK(role IN ('admin','analyst','viewer')),active boolean NOT NULL DEFAULT true,created_at timestamptz NOT NULL DEFAULT now(),UNIQUE(org_id,email));
CREATE TABLE documents(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),org_id uuid NOT NULL REFERENCES organisations(id),uploaded_by uuid NOT NULL REFERENCES users(id),filename text NOT NULL,mime_type text NOT NULL,status text NOT NULL CHECK(status IN ('processing','ready','failed')),chunk_count integer NOT NULL DEFAULT 0,created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE document_chunks(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),org_id uuid NOT NULL REFERENCES organisations(id),document_id uuid NOT NULL REFERENCES documents(id) ON DELETE CASCADE,chunk_index integer NOT NULL,page_number integer,content text NOT NULL,embedding vector(768) NOT NULL,metadata jsonb NOT NULL DEFAULT '{}',created_at timestamptz NOT NULL DEFAULT now(),UNIQUE(document_id,chunk_index));
CREATE INDEX document_chunks_embedding_idx ON document_chunks USING hnsw (embedding vector_cosine_ops);
CREATE INDEX document_chunks_org_idx ON document_chunks(org_id);
CREATE TABLE customers(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),org_id uuid NOT NULL REFERENCES organisations(id),name text NOT NULL,industry text);
CREATE TABLE sales(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),org_id uuid NOT NULL REFERENCES organisations(id),customer_id uuid REFERENCES customers(id),sale_date date NOT NULL,amount numeric(14,2) NOT NULL CHECK(amount>=0));
CREATE INDEX sales_org_date_idx ON sales(org_id,sale_date);
CREATE TABLE financial_records(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),org_id uuid NOT NULL REFERENCES organisations(id),record_date date NOT NULL,category text NOT NULL,amount numeric(14,2) NOT NULL,description text);
CREATE TABLE operational_records(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),org_id uuid NOT NULL REFERENCES organisations(id),occurred_at timestamptz NOT NULL,category text NOT NULL,severity text NOT NULL,description text);
CREATE TABLE business_metrics(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),org_id uuid NOT NULL REFERENCES organisations(id),metric_key text NOT NULL,metric_date date NOT NULL,value numeric(18,4) NOT NULL,metadata jsonb NOT NULL DEFAULT '{}',UNIQUE(org_id,metric_key,metric_date));
CREATE TABLE audit_logs(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),org_id uuid REFERENCES organisations(id),actor_id uuid REFERENCES users(id),event_type text NOT NULL,metadata jsonb NOT NULL DEFAULT '{}',created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE ai_analysis_requests(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),org_id uuid NOT NULL REFERENCES organisations(id),user_id uuid NOT NULL REFERENCES users(id),question_hash text NOT NULL,analysis_type text,status text NOT NULL,created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE ai_analysis_results(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),request_id uuid NOT NULL REFERENCES ai_analysis_requests(id) ON DELETE CASCADE,result jsonb NOT NULL,created_at timestamptz NOT NULL DEFAULT now());
